# Generated by Django 3.2 on 2022-07-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
