# Generated by Django 3.2 on 2022-07-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=900, null=True, verbose_name='Descripción'),
        ),
    ]
